name: absensi_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  camera: ^0.11.0+1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  lottie: ^3.0.0
  google_mlkit_face_detection: ^0.11.0
  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/raw/